### ISSUE TITLE
Use case scenarios for Akka.js

### ISSUE THREAD

**Issue by yawnt** [unicredit/akka.js#12]
I'm collecting some potential use cases for akka.js, if anyone has ideas please do feel free to contribute!
#### Distributed chat application

![](http://i.imgur.com/Y8N9vXw.png)

In this example we have multiple clients (browsers) on which an actor system is running and for each actor system 1-n actors taking care of the UI of the chat. Communication would be done through `akka-remote` with WebRTC as a transport layer.
The interesting part here is that the existing Akka infrastructure for message delivery can be leveraged to allow the programmer to be completely oblivious about the inner workings of WebRTC
#### Browser UI Framework

![](http://i.imgur.com/iXftMtd.png)

In this example we have an Actor which is listening for DOM events and reacts to them. By composing actor behaviour and encapsulate each element's status inside an actor, we can create reactive dead-simple UIs.
This approach is interesting because it frees the programmer from the constraints of the DOM model and could potentially be a platform on top of which one can build DOM optimizations (diff'ing etc)

example:
https://github.com/unicredit/akka.js-examples/tree/master/calculator
#### Cross-compilable libraries

![](http://i.imgur.com/C5F7iB8.png)

In this example we have two projects: a Scala one ("server.scala") and a client one ("client.scala"). Once they are compiled they run in their respective environments (JVM for Akka.JVM, JS VM for Akka.js) but they can still communicate transparently through WebSockets. 
This is interesting because it would allow to use one single abstraction for all communications, in a sense it's the complementary of what Play already does in handling WebSockets with Akka actors in the backend.
#### Visualization Tool

![](http://i.imgur.com/pyDH69m.png)

In this example we have a code ("algorithm.scala") implementing an algorithm which runs on a JVM backend ("SERVER"), but which if need be, can also run in the frontend through Akka.js. A visualization interface can easily be built which plugs into the algorithm in a step-by-step fashion and shows each step, thus making the explanation much easier.
The interesting thing is, we could leverage all the existing algorithms already implemented in Akka!

example:
https://github.com/unicredit/akka.js-examples/tree/master/raft
#### Multicore Computing

![](http://i.imgur.com/IHLuUMk.png)

JS has historically being a single threaded language and it remains so to this date, however Web Workers provide a way for the "main" thread to spawn more JS VMs and interact with them through message passing. This mechanism allows to perform heavy computation off the UI thread which is thus still responsive to user events.
Unfortunately the message passing API only supports few data structures and Akka.js (through it's built-in serialization) would be able to make working with Web Workers a much more seamless experience. It could also potentially evolve into an optimization if the serialization were to be done into ArrayBuffers which are then sent as Transferable Objects

I think that the idea behind these projects is that a higher level abstraction in the browser, combined with Akka's maturity would open up doors to a bunch of new applications which were previously very cumbersome to develop in vanilla JS

In case you have any questions about the above, please do feel free to ask :D

@rkuhn @andreaTP @andreaferretti

**Comment by jducoeur** [comment]
The Browser UI Framework use case is the one that I find especially intriguing -- it's been bubbling around in the back of my brain for at least six months now.  If we had strong Akka support client-side, then it seems to lead towards a whole Akka-based UI framework, where all of the mutable UI components get wrapped in Actors along the lines shown above.

The real power of that, though, comes when you add a clean client-side implementation of akka-streaming, standardized Websockets, and decent abstractions for plugging streams together across the JS/JVM boundary.  (Possibly a la Autowire, at least conceptually.)  At that point, you could have client-side UI components seamlessly streaming their changes across to the underlying back-end data, and vice versa.  That expands the Akka world into what might be a really compelling new client/server framework.

(I confess to having mixed feelings here, solely because I'd likely decide to rewrite Querki's UI yet again in terms of it.  But wow, it's potentially pretty fabulous...)

**Comment by yawnt** [comment]
The idea is @andreaferretti 's actually.
If you want to give it a shot, client-side Akka actors do work, so you could quickly code a  limited demo showing the concept :D

**Comment by jducoeur** [comment]
Don't have time right at the moment, but I'm pondering what the architecture will eventually be for me to do server-to-client reactive feedback, updating the UI dynamically as the underlying server-side data changes.  This is one of the more intriguing possibilities...

**Comment by yawnt** [comment]
Some sort of pub-sub that streams to the client (from Akka.JVM to Akka.js) should do the trick. The problem would be keeping everything lightweight and responsive, I think.

**Comment by stoke** [comment]
Yeah, i'm looking forward to the browser UI framework, especially because it opens possibilities to something like [nw.js](http://nwjs.io/)

**Comment by ghost** [comment]
The [LDP](http://www.w3.org/TR/ldp/) "describes the use of HTTP for accessing, updating, creating and deleting resources from servers that expose their resources as Linked Data", essentially RDF.

So akka.js could be part of such a framework, perhaps even proving a local LDP server.

**Comment by ghost** [comment]
As an example, here is a [pure JS version](https://github.com/linkeddata/ldnode) that uses webs sockets. Other than that, I know little about that project

**Comment by bblfish** [comment]
Hi, I am not so convinced about client/server communication over akka, as for that to work on a global scale one would need everyone to adopt akka - this is an important restriction of course only because I am interested in global communication: ie a client that can fetch data from any web server using LDP by following links. But having said that, I'd not stop anyone there. On the other hand akka and web workers makes a lot of sense... ( since there is a closed world assumption there )

What I think is more intriguing is the potential for reactive frameworks like [cyle.js](https://github.com/staltz/cycle) that builds on [RxJS, the Reactive Extensions for JavaScript](https://github.com/Reactive-Extensions/RxJS) and the same virtual Dom concept used by [Facebook's React](https://facebook.github.io/react/) - though he uses [Virtual DOM](https://github.com/Matt-Esch/virtual-dom). Cycle.js seems to have gone beyond FB React in that it tries to be entirely reactive, and purely functional as explained on the github site and in [this longer article](http://futurice.com/blog/reactive-mvc-and-the-virtual-dom). ( see also the [recent slides](https://speakerdeck.com/staltz/what-if-the-user-was-a-function) ).

Ok so why do I mention Cycle.js which I have only just discovered? Well simply that since Reactive Streams is built on akka and are competing with RxJS then one could imagine a version of Cycle.js built on Reactive Streams. If Cycle.JS has it right then this could have the same properties. Furthermore it would be very interesting if the same code using reactive streams could be run on the client AND on the server. The server could fetch remote resources all over the web, and build up quick initial views in html which could then be continued to be built up by the client.  It remains that all global interactions would be akka agnostic, and web standards compliant so that the client could even make direct requests to remote resources if needed without breaking any of the logic.... ( no: if this is my server then do this, else if this is another server do this... other than going through proxies... )

**Comment by bblfish** [comment]
Btw, along those lines @ochrons [has a great guide](http://ochrons.github.io/scalajs-spa-tutorial/todo-module-and-data-flow.html) on how to use Facebook React with a simple actor system he put together to implement the Flux part of the React architecture.  There akka.js could be used immediately.

**Comment by marciol** [comment]
I don't know if you are aware of this project https://github.com/hypernumbers/LuvvieScript, that aims to bring erlang code to the frontend.

**Comment by andreaTP** [comment]
@marciol unfortunately looks not maintained anymore...

**Comment by yawnt** [comment]
A couple of examples from https://github.com/unicredit/akka.js-examples
- `calculator/` implements something akin to the UI framework (very very simplified)
- `raft/` visualizes an algorithm and uses multicore to run the code

**Comment by bblfish** [comment]
Perhaps  Actors could be very useful in interfacing with IndexDB, as discussed [in issue 1 of scalajs-rx-idb](https://github.com/viagraphs/scalajs-rx-idb/issues/1). Actors could hide the type of storage allowing saving to IndexDB when its available, or falling back to WebSQL which is still more widely available on older browsers. In fact one could imagine building a whole data caching system with actors, which would first check the local DB or fetch resources remotely. Here [Location Transparency](http://www.reactivemanifesto.org/glossary#Location-Transparency) should come in very useful as it would allow a system to be built and to work on many different kinds of browsers, taking into account whether they support WebWorkers or not, IndexDB or not, and fall back to storage on the server if needed. Actors as Finite State Machines could parse data from the web in chunks iteratively to allow other actors to proceed with their work. It would be interesting to understand how this would tie in with reactive backpressure aware streams.

**Comment by bblfish** [comment]
I pointed to [this issue in the forum of the Reactive Design Patterns Book](https://forums.manning.com/posts/list/36205.page#p101140).

**Comment by schrepfler** [comment]
I don't see any approach where we have for example Java/Scala akka actor system sending natively messages to node.js akka backends?

**Comment by andreaTP** [comment]
It is totally doable, we have POCs of that, the idea is to have a reflection free pickler and use different channels for the communications, like web sockets... Still a lot of work to do to achieve this goal reliably

**Comment by michaelahlers** [comment]
Is it conceivable to implement `akka.remote.transport.Transport` on top of WebSockets or long-lived HTTP requests?

**Comment by andreaTP** [comment]
yes, it is, as well as Javascript channels and maybe WebRTC

**Comment by michaelahlers** [comment]
@andreaTP, I've a few vague ideas of how this could work in practice. (Seems tricky to me in that only one side can initiate the association.) You have any thoughts on implementation details? (Internet addresses aren't useful, but I imagine client actor systems would be uniquely identified and employed for `Transport.isResponsibleFor`.) On another note, I want to do this because it could be incredibly powerful (in part for removing serialization concerns to Akka, and especially when combined with at-least-once delivery for both client-to-server and server-to-client messages) but then [Artery](http://doc.akka.io/docs/akka/current/scala/remoting-artery.html) is slated to kill pluggable transports. (See [follow up conversation on Gitter](https://gitter.im/akkajs/Lobby?at=59357e06f2dd2dba066f9b35).)

**Comment by andreaTP** [comment]
let have a quick chat over Gitter it will be easier :-)

**Comment by pishen** [comment]
Tried to build a FRP tool based on Akka.js. Thanks for porting Akka to Scala.js to make this possible.
https://github.com/pishen/akka-ui

**Comment by andreaTP** [comment]
looks great! @pishen could I add a link to your project to the Readme file?

**Comment by pishen** [comment]
@andreaTP of course!

**Comment by bulkazszynka** [comment]
Is there any example of running a WebWorker? Or at least a hint how to do it?

**Comment by andreaTP** [comment]
Hi @bulkazszynka thanks for your interest!
I think the best example to start with is here:
https://github.com/akka-js/akka.js-dom/blob/master/work.js#L148

Is in Js, for doing the same with Scala.Js you probably need to invest some time in automating the packaging etc....
let me know if it works for you!
