### ISSUE TITLE
JS/JVM code separation

### ISSUE THREAD

**Issue by yawnt** [unicredit/akka.js#14]
Most of the code can be shared between Akka.JVM and Akka.js so my proposal is, for `akka-actor`, to adopt the standard layout of cross-compilable Scala-js modules which is the following
- one `shared/` directory with shared code
- one `js/` directory with JS specific implementations
- one `jvm/` directory with JVM specific implementations

@rkuhn @andreaTP @andreaferretti

**Comment by rkuhn** [comment]
Hmm, do you mean that akka/akka shall change as well? That is rather unlikely to happen in the near term, we should be clear about that this effort is a separate one for now, building upon the Akka source and enhancing it to work with ScalaJS.

For this it would be apt to factor out the differences—that allows easy review as well as easy merges with upstream Akka. It should be possible to write some sbt magic that overrides the sources that are in `src/main/scala` partially with files from `src/main/scala-js`, and then you’d keep a pristine copy in `scala` and only copy&modify those files into `scala-js` that need changes. For IDE support you could copy all files that are used unchanged into `target/scala-jvm` and use that instead of the normal `src/main/scala` for the build path configuration.

**Comment by yawnt** [comment]
work for this currently being done in the [merge-js](https://github.com/unicredit/akka.js/tree/merge-js) branch

**Comment by huntc** [comment]
Perhaps consider new packages only for specific targets while retaining the core as-is:
- one js/ directory with JS specific implementations
- one jdk/ directory with JDK specific implementations

Note also that the JDK is the target, not JVM.

**Comment by yawnt** [comment]
hi @huntc, thank you for your input!
the structure of the project is dictated by the way Scala.js sets up cross-project builds (more infos [here](http://www.scala-js.org/doc/sbt/cross-building.html)) and I think it would be best to stick to the community standard :)

**Comment by andreaTP** [comment]
This is completely targeted on a branch so it can be safely closed
