### ISSUE TITLE
make it pickler agnostic

### ISSUE THREAD

**Issue by antonkulaga** [unicredit/akka.js#22]
There are many pickling libs and scalajs-pickling is definitely not the best one. I suggest to make websocket implementation pickler-agnostic (like it is with autowire) so people will be able to choose favourite pickling libs, like BooPickler, Prickle, UPickler and so on.

**Comment by andreaTP** [comment]
At the moment we  are going to get a  try with the next version of Scala pickling but, if we cannot reach a static( let say macro time) Any type serialisation we will goon your good proposal. Thanks!

**Comment by yawnt** [comment]
closing this for the time being, because the problem really lies in the fact that `Any` cannot be serialized by any known library (with the exception of `scala-js-pickling`, which unfortunately requires explicit registration of picklers/unpicklers)
Once reflection and the new version of 'Scala Pickling' rolls out, we should be able to move forward :)

Feel free to reopen it, should anything change!

PS: the plan is to rewrite both WebSocket and WebWorker as transport layers of `akka-remote`, so those libraries should be treated as proof of concepts and not part of the akka.js initiative for the time being :)
