### ISSUE TITLE
verify ActorMaterializer can register it's extension without modifying original ActorSystem

### ISSUE THREAD

**Issue by andreaTP** [unicredit/akka.js#34]
Like we did for Logs we need to realize if this is feasible or have an acceptable alternative that can be pushed back to akka master

**Comment by andreaTP** [comment]
Done

**Comment by solomono** [comment]
It seems you  changed a couple of files to implement this solution. In this case is it simply that you wish to avoid modifying ActorSystem as this is an important file. I am trying to understand your heuristics for determining how we resolve problems where there is a difference in behavior. I would hope that my can reasoning can become similar to yours so that my pull request can be accepted without change and therefore  I can minimize your work

**Comment by andreaTP** [comment]
Cool! please keep in touch and I'm sure we can easily agree on any point :-)

**Comment by solomono** [comment]
Please do not misconstrue my tone. Perhaps I have lived in the US too long and I am too direct You are the master with regard to Scala.js porting and I am the student. And besides this is your project. If I have an opinion I will render it.But my goal here was to understand your way of thinking so that I can make the decisions consistent with your approach

**Comment by andreaTP** [comment]
I was totally direct with you too, I really appreciate this approach! :-)
I just say that I consider any suggestion like yours important, I'm not a teacher of anything ... please feel free to open discussion issues on points where you have a diverging opinion and I will explain my position, could be really useful!

Yep you got it right on the ActorSystem thing, it is a huge file and I really need to minimize my effort on it, otherwise keeping it aligned could get me troubles.
What will happen in the middle-term future is that I should propose a different extension loading algorithm to mainstream akka or, at least, isolate that behavior in a separate file so that it could freely diverge.
